// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TripTrackerProto.proto

package com.taraan.dum.dto.protobuf;

public final class TripTrackerInfoProtocol {
    private TripTrackerInfoProtocol() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface TripTrackerInfoDtosOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protocol.TripTrackerInfoDtos)
            com.google.protobuf.MessageOrBuilder {



        java.util.List<com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto>
        getOdpTripTrackerInfosList();



        com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto getOdpTripTrackerInfos(int index);



        int getOdpTripTrackerInfosCount();


        java.util.List<? extends com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder>
        getOdpTripTrackerInfosOrBuilderList();

        com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder getOdpTripTrackerInfosOrBuilder(
                int index);
    }



    public static final class TripTrackerInfoDtos extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:protocol.TripTrackerInfoDtos)
            TripTrackerInfoDtosOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use TripTrackerInfoDtos.newBuilder() to construct.
        private TripTrackerInfoDtos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TripTrackerInfoDtos() {
            odpTripTrackerInfos_ = java.util.Collections.emptyList();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private TripTrackerInfoDtos(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                odpTripTrackerInfos_ = new java.util.ArrayList<com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            odpTripTrackerInfos_.add(
                                    input.readMessage(com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    odpTripTrackerInfos_ = java.util.Collections.unmodifiableList(odpTripTrackerInfos_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_TripTrackerInfoDtos_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_TripTrackerInfoDtos_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos.class, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos.Builder.class);
        }

        public static final int ODPTRIPTRACKERINFOS_FIELD_NUMBER = 4;
        private java.util.List<com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto> odpTripTrackerInfos_;



        public java.util.List<com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto> getOdpTripTrackerInfosList() {
            return odpTripTrackerInfos_;
        }



        public java.util.List<? extends com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder>
        getOdpTripTrackerInfosOrBuilderList() {
            return odpTripTrackerInfos_;
        }



        public int getOdpTripTrackerInfosCount() {
            return odpTripTrackerInfos_.size();
        }



        public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto getOdpTripTrackerInfos(int index) {
            return odpTripTrackerInfos_.get(index);
        }



        public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder getOdpTripTrackerInfosOrBuilder(
                int index) {
            return odpTripTrackerInfos_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < odpTripTrackerInfos_.size(); i++) {
                output.writeMessage(4, odpTripTrackerInfos_.get(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < odpTripTrackerInfos_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, odpTripTrackerInfos_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos)) {
                return super.equals(obj);
            }
            com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos other = (com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos) obj;

            boolean result = true;
            result = result && getOdpTripTrackerInfosList()
                    .equals(other.getOdpTripTrackerInfosList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getOdpTripTrackerInfosCount() > 0) {
                hash = (37 * hash) + ODPTRIPTRACKERINFOS_FIELD_NUMBER;
                hash = (53 * hash) + getOdpTripTrackerInfosList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }



        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protocol.TripTrackerInfoDtos)
                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtosOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_TripTrackerInfoDtos_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_TripTrackerInfoDtos_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos.class, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos.Builder.class);
            }

            // Construct using com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getOdpTripTrackerInfosFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                if (odpTripTrackerInfosBuilder_ == null) {
                    odpTripTrackerInfos_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    odpTripTrackerInfosBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_TripTrackerInfoDtos_descriptor;
            }

            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos getDefaultInstanceForType() {
                return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos.getDefaultInstance();
            }

            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos build() {
                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos buildPartial() {
                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos result = new com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos(this);
                int from_bitField0_ = bitField0_;
                if (odpTripTrackerInfosBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        odpTripTrackerInfos_ = java.util.Collections.unmodifiableList(odpTripTrackerInfos_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.odpTripTrackerInfos_ = odpTripTrackerInfos_;
                } else {
                    result.odpTripTrackerInfos_ = odpTripTrackerInfosBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos) {
                    return mergeFrom((com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos other) {
                if (other == com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos.getDefaultInstance())
                    return this;
                if (odpTripTrackerInfosBuilder_ == null) {
                    if (!other.odpTripTrackerInfos_.isEmpty()) {
                        if (odpTripTrackerInfos_.isEmpty()) {
                            odpTripTrackerInfos_ = other.odpTripTrackerInfos_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureOdpTripTrackerInfosIsMutable();
                            odpTripTrackerInfos_.addAll(other.odpTripTrackerInfos_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.odpTripTrackerInfos_.isEmpty()) {
                        if (odpTripTrackerInfosBuilder_.isEmpty()) {
                            odpTripTrackerInfosBuilder_.dispose();
                            odpTripTrackerInfosBuilder_ = null;
                            odpTripTrackerInfos_ = other.odpTripTrackerInfos_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            odpTripTrackerInfosBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getOdpTripTrackerInfosFieldBuilder() : null;
                        } else {
                            odpTripTrackerInfosBuilder_.addAllMessages(other.odpTripTrackerInfos_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.util.List<com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto> odpTripTrackerInfos_ =
                    java.util.Collections.emptyList();

            private void ensureOdpTripTrackerInfosIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    odpTripTrackerInfos_ = new java.util.ArrayList<com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto>(odpTripTrackerInfos_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder> odpTripTrackerInfosBuilder_;



            public java.util.List<com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto> getOdpTripTrackerInfosList() {
                if (odpTripTrackerInfosBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(odpTripTrackerInfos_);
                } else {
                    return odpTripTrackerInfosBuilder_.getMessageList();
                }
            }



            public int getOdpTripTrackerInfosCount() {
                if (odpTripTrackerInfosBuilder_ == null) {
                    return odpTripTrackerInfos_.size();
                } else {
                    return odpTripTrackerInfosBuilder_.getCount();
                }
            }


            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto getOdpTripTrackerInfos(int index) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    return odpTripTrackerInfos_.get(index);
                } else {
                    return odpTripTrackerInfosBuilder_.getMessage(index);
                }
            }


            public Builder setOdpTripTrackerInfos(
                    int index, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto value) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOdpTripTrackerInfosIsMutable();
                    odpTripTrackerInfos_.set(index, value);
                    onChanged();
                } else {
                    odpTripTrackerInfosBuilder_.setMessage(index, value);
                }
                return this;
            }



            public Builder setOdpTripTrackerInfos(
                    int index, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder builderForValue) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    ensureOdpTripTrackerInfosIsMutable();
                    odpTripTrackerInfos_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    odpTripTrackerInfosBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }



            public Builder addOdpTripTrackerInfos(com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto value) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOdpTripTrackerInfosIsMutable();
                    odpTripTrackerInfos_.add(value);
                    onChanged();
                } else {
                    odpTripTrackerInfosBuilder_.addMessage(value);
                }
                return this;
            }


            public Builder addOdpTripTrackerInfos(
                    int index, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto value) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOdpTripTrackerInfosIsMutable();
                    odpTripTrackerInfos_.add(index, value);
                    onChanged();
                } else {
                    odpTripTrackerInfosBuilder_.addMessage(index, value);
                }
                return this;
            }


            public Builder addOdpTripTrackerInfos(
                    com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder builderForValue) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    ensureOdpTripTrackerInfosIsMutable();
                    odpTripTrackerInfos_.add(builderForValue.build());
                    onChanged();
                } else {
                    odpTripTrackerInfosBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }


            public Builder addOdpTripTrackerInfos(
                    int index, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder builderForValue) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    ensureOdpTripTrackerInfosIsMutable();
                    odpTripTrackerInfos_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    odpTripTrackerInfosBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllOdpTripTrackerInfos(
                    Iterable<? extends com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto> values) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    ensureOdpTripTrackerInfosIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, odpTripTrackerInfos_);
                    onChanged();
                } else {
                    odpTripTrackerInfosBuilder_.addAllMessages(values);
                }
                return this;
            }


            public Builder clearOdpTripTrackerInfos() {
                if (odpTripTrackerInfosBuilder_ == null) {
                    odpTripTrackerInfos_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    odpTripTrackerInfosBuilder_.clear();
                }
                return this;
            }



            public Builder removeOdpTripTrackerInfos(int index) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    ensureOdpTripTrackerInfosIsMutable();
                    odpTripTrackerInfos_.remove(index);
                    onChanged();
                } else {
                    odpTripTrackerInfosBuilder_.remove(index);
                }
                return this;
            }



            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder getOdpTripTrackerInfosBuilder(
                    int index) {
                return getOdpTripTrackerInfosFieldBuilder().getBuilder(index);
            }



            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder getOdpTripTrackerInfosOrBuilder(
                    int index) {
                if (odpTripTrackerInfosBuilder_ == null) {
                    return odpTripTrackerInfos_.get(index);
                } else {
                    return odpTripTrackerInfosBuilder_.getMessageOrBuilder(index);
                }
            }



            public java.util.List<? extends com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder>
            getOdpTripTrackerInfosOrBuilderList() {
                if (odpTripTrackerInfosBuilder_ != null) {
                    return odpTripTrackerInfosBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(odpTripTrackerInfos_);
                }
            }



            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder addOdpTripTrackerInfosBuilder() {
                return getOdpTripTrackerInfosFieldBuilder().addBuilder(
                        com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.getDefaultInstance());
            }



            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder addOdpTripTrackerInfosBuilder(
                    int index) {
                return getOdpTripTrackerInfosFieldBuilder().addBuilder(
                        index, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.getDefaultInstance());
            }



            public java.util.List<com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder>
            getOdpTripTrackerInfosBuilderList() {
                return getOdpTripTrackerInfosFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder>
            getOdpTripTrackerInfosFieldBuilder() {
                if (odpTripTrackerInfosBuilder_ == null) {
                    odpTripTrackerInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder>(
                            odpTripTrackerInfos_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    odpTripTrackerInfos_ = null;
                }
                return odpTripTrackerInfosBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:protocol.TripTrackerInfoDtos)
        }

        // @@protoc_insertion_point(class_scope:protocol.TripTrackerInfoDtos)
        private static final com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos();
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TripTrackerInfoDtos>
                PARSER = new com.google.protobuf.AbstractParser<TripTrackerInfoDtos>() {
            public TripTrackerInfoDtos parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TripTrackerInfoDtos(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TripTrackerInfoDtos> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<TripTrackerInfoDtos> getParserForType() {
            return PARSER;
        }

        public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.TripTrackerInfoDtos getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface OdpTripTrackerInfoDtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protocol.OdpTripTrackerInfoDto)
            com.google.protobuf.MessageOrBuilder {



        long getOrder();



        String getDeviceId();


        com.google.protobuf.ByteString
        getDeviceIdBytes();



        double getLongitude();



        double getLatitude();



        double getX();



        double getY();


        double getZ();



        double getSumAcceleration();



        double getRealSpeed();



        long getDirection1();



        String getPostDate();



        com.google.protobuf.ByteString
        getPostDateBytes();
    }



    public static final class OdpTripTrackerInfoDto extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:protocol.OdpTripTrackerInfoDto)
            OdpTripTrackerInfoDtoOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use OdpTripTrackerInfoDto.newBuilder() to construct.
        private OdpTripTrackerInfoDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private OdpTripTrackerInfoDto() {
            order_ = 0L;
            deviceId_ = "";
            longitude_ = 0D;
            latitude_ = 0D;
            x_ = 0D;
            y_ = 0D;
            z_ = 0D;
            sumAcceleration_ = 0D;
            realSpeed_ = 0D;
            direction1_ = 0L;
            postDate_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private OdpTripTrackerInfoDto(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            order_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            deviceId_ = s;
                            break;
                        }
                        case 25: {

                            longitude_ = input.readDouble();
                            break;
                        }
                        case 33: {

                            latitude_ = input.readDouble();
                            break;
                        }
                        case 41: {

                            x_ = input.readDouble();
                            break;
                        }
                        case 49: {

                            y_ = input.readDouble();
                            break;
                        }
                        case 57: {

                            z_ = input.readDouble();
                            break;
                        }
                        case 65: {

                            sumAcceleration_ = input.readDouble();
                            break;
                        }
                        case 73: {

                            realSpeed_ = input.readDouble();
                            break;
                        }
                        case 80: {

                            direction1_ = input.readInt64();
                            break;
                        }
                        case 90: {
                            String s = input.readStringRequireUtf8();

                            postDate_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_OdpTripTrackerInfoDto_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_OdpTripTrackerInfoDto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.class, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder.class);
        }

        public static final int ORDER_FIELD_NUMBER = 1;
        private long order_;



        public long getOrder() {
            return order_;
        }

        public static final int DEVICEID_FIELD_NUMBER = 2;
        private volatile Object deviceId_;



        public String getDeviceId() {
            Object ref = deviceId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                deviceId_ = s;
                return s;
            }
        }



        public com.google.protobuf.ByteString
        getDeviceIdBytes() {
            Object ref = deviceId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                deviceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LONGITUDE_FIELD_NUMBER = 3;
        private double longitude_;



        public double getLongitude() {
            return longitude_;
        }

        public static final int LATITUDE_FIELD_NUMBER = 4;
        private double latitude_;



        public double getLatitude() {
            return latitude_;
        }

        public static final int X_FIELD_NUMBER = 5;
        private double x_;



        public double getX() {
            return x_;
        }

        public static final int Y_FIELD_NUMBER = 6;
        private double y_;



        public double getY() {
            return y_;
        }

        public static final int Z_FIELD_NUMBER = 7;
        private double z_;



        public double getZ() {
            return z_;
        }

        public static final int SUMACCELERATION_FIELD_NUMBER = 8;
        private double sumAcceleration_;



        public double getSumAcceleration() {
            return sumAcceleration_;
        }

        public static final int REALSPEED_FIELD_NUMBER = 9;
        private double realSpeed_;



        public double getRealSpeed() {
            return realSpeed_;
        }

        public static final int DIRECTION1_FIELD_NUMBER = 10;
        private long direction1_;



        public long getDirection1() {
            return direction1_;
        }

        public static final int POSTDATE_FIELD_NUMBER = 11;
        private volatile Object postDate_;


        public String getPostDate() {
            Object ref = postDate_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                postDate_ = s;
                return s;
            }
        }


        public com.google.protobuf.ByteString
        getPostDateBytes() {
            Object ref = postDate_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                postDate_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (order_ != 0L) {
                output.writeInt64(1, order_);
            }
            if (!getDeviceIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
            }
            if (longitude_ != 0D) {
                output.writeDouble(3, longitude_);
            }
            if (latitude_ != 0D) {
                output.writeDouble(4, latitude_);
            }
            if (x_ != 0D) {
                output.writeDouble(5, x_);
            }
            if (y_ != 0D) {
                output.writeDouble(6, y_);
            }
            if (z_ != 0D) {
                output.writeDouble(7, z_);
            }
            if (sumAcceleration_ != 0D) {
                output.writeDouble(8, sumAcceleration_);
            }
            if (realSpeed_ != 0D) {
                output.writeDouble(9, realSpeed_);
            }
            if (direction1_ != 0L) {
                output.writeInt64(10, direction1_);
            }
            if (!getPostDateBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 11, postDate_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (order_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, order_);
            }
            if (!getDeviceIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
            }
            if (longitude_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(3, longitude_);
            }
            if (latitude_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(4, latitude_);
            }
            if (x_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(5, x_);
            }
            if (y_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(6, y_);
            }
            if (z_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(7, z_);
            }
            if (sumAcceleration_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(8, sumAcceleration_);
            }
            if (realSpeed_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(9, realSpeed_);
            }
            if (direction1_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(10, direction1_);
            }
            if (!getPostDateBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, postDate_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto)) {
                return super.equals(obj);
            }
            com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto other = (com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto) obj;

            boolean result = true;
            result = result && (getOrder()
                    == other.getOrder());
            result = result && getDeviceId()
                    .equals(other.getDeviceId());
            result = result && (
                    Double.doubleToLongBits(getLongitude())
                            == Double.doubleToLongBits(
                            other.getLongitude()));
            result = result && (
                    Double.doubleToLongBits(getLatitude())
                            == Double.doubleToLongBits(
                            other.getLatitude()));
            result = result && (
                    Double.doubleToLongBits(getX())
                            == Double.doubleToLongBits(
                            other.getX()));
            result = result && (
                    Double.doubleToLongBits(getY())
                            == Double.doubleToLongBits(
                            other.getY()));
            result = result && (
                    Double.doubleToLongBits(getZ())
                            == Double.doubleToLongBits(
                            other.getZ()));
            result = result && (
                    Double.doubleToLongBits(getSumAcceleration())
                            == Double.doubleToLongBits(
                            other.getSumAcceleration()));
            result = result && (
                    Double.doubleToLongBits(getRealSpeed())
                            == Double.doubleToLongBits(
                            other.getRealSpeed()));
            result = result && (getDirection1()
                    == other.getDirection1());
            result = result && getPostDate()
                    .equals(other.getPostDate());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ORDER_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getOrder());
            hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
            hash = (53 * hash) + getDeviceId().hashCode();
            hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getLongitude()));
            hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getLatitude()));
            hash = (37 * hash) + X_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getX()));
            hash = (37 * hash) + Y_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getY()));
            hash = (37 * hash) + Z_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getZ()));
            hash = (37 * hash) + SUMACCELERATION_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getSumAcceleration()));
            hash = (37 * hash) + REALSPEED_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getRealSpeed()));
            hash = (37 * hash) + DIRECTION1_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getDirection1());
            hash = (37 * hash) + POSTDATE_FIELD_NUMBER;
            hash = (53 * hash) + getPostDate().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }



        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protocol.OdpTripTrackerInfoDto)
                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_OdpTripTrackerInfoDto_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_OdpTripTrackerInfoDto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.class, com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.Builder.class);
            }

            // Construct using com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                order_ = 0L;

                deviceId_ = "";

                longitude_ = 0D;

                latitude_ = 0D;

                x_ = 0D;

                y_ = 0D;

                z_ = 0D;

                sumAcceleration_ = 0D;

                realSpeed_ = 0D;

                direction1_ = 0L;

                postDate_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.internal_static_protocol_OdpTripTrackerInfoDto_descriptor;
            }

            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto getDefaultInstanceForType() {
                return com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.getDefaultInstance();
            }

            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto build() {
                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto buildPartial() {
                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto result = new com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto(this);
                result.order_ = order_;
                result.deviceId_ = deviceId_;
                result.longitude_ = longitude_;
                result.latitude_ = latitude_;
                result.x_ = x_;
                result.y_ = y_;
                result.z_ = z_;
                result.sumAcceleration_ = sumAcceleration_;
                result.realSpeed_ = realSpeed_;
                result.direction1_ = direction1_;
                result.postDate_ = postDate_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto) {
                    return mergeFrom((com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto other) {
                if (other == com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto.getDefaultInstance())
                    return this;
                if (other.getOrder() != 0L) {
                    setOrder(other.getOrder());
                }
                if (!other.getDeviceId().isEmpty()) {
                    deviceId_ = other.deviceId_;
                    onChanged();
                }
                if (other.getLongitude() != 0D) {
                    setLongitude(other.getLongitude());
                }
                if (other.getLatitude() != 0D) {
                    setLatitude(other.getLatitude());
                }
                if (other.getX() != 0D) {
                    setX(other.getX());
                }
                if (other.getY() != 0D) {
                    setY(other.getY());
                }
                if (other.getZ() != 0D) {
                    setZ(other.getZ());
                }
                if (other.getSumAcceleration() != 0D) {
                    setSumAcceleration(other.getSumAcceleration());
                }
                if (other.getRealSpeed() != 0D) {
                    setRealSpeed(other.getRealSpeed());
                }
                if (other.getDirection1() != 0L) {
                    setDirection1(other.getDirection1());
                }
                if (!other.getPostDate().isEmpty()) {
                    postDate_ = other.postDate_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long order_;



            public long getOrder() {
                return order_;
            }



            public Builder setOrder(long value) {

                order_ = value;
                onChanged();
                return this;
            }



            public Builder clearOrder() {

                order_ = 0L;
                onChanged();
                return this;
            }

            private Object deviceId_ = "";



            public String getDeviceId() {
                Object ref = deviceId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    deviceId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }



            public com.google.protobuf.ByteString
            getDeviceIdBytes() {
                Object ref = deviceId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    deviceId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }



            public Builder setDeviceId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                deviceId_ = value;
                onChanged();
                return this;
            }



            public Builder clearDeviceId() {

                deviceId_ = getDefaultInstance().getDeviceId();
                onChanged();
                return this;
            }



            public Builder setDeviceIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                deviceId_ = value;
                onChanged();
                return this;
            }

            private double longitude_;



            public double getLongitude() {
                return longitude_;
            }



            public Builder setLongitude(double value) {

                longitude_ = value;
                onChanged();
                return this;
            }



            public Builder clearLongitude() {

                longitude_ = 0D;
                onChanged();
                return this;
            }

            private double latitude_;



            public double getLatitude() {
                return latitude_;
            }



            public Builder setLatitude(double value) {

                latitude_ = value;
                onChanged();
                return this;
            }



            public Builder clearLatitude() {

                latitude_ = 0D;
                onChanged();
                return this;
            }

            private double x_;



            public double getX() {
                return x_;
            }


            public Builder setX(double value) {

                x_ = value;
                onChanged();
                return this;
            }


            public Builder clearX() {

                x_ = 0D;
                onChanged();
                return this;
            }

            private double y_;



            public double getY() {
                return y_;
            }



            public Builder setY(double value) {

                y_ = value;
                onChanged();
                return this;
            }



            public Builder clearY() {

                y_ = 0D;
                onChanged();
                return this;
            }

            private double z_;



            public double getZ() {
                return z_;
            }



            public Builder setZ(double value) {

                z_ = value;
                onChanged();
                return this;
            }


            public Builder clearZ() {

                z_ = 0D;
                onChanged();
                return this;
            }

            private double sumAcceleration_;


            public double getSumAcceleration() {
                return sumAcceleration_;
            }



            public Builder setSumAcceleration(double value) {

                sumAcceleration_ = value;
                onChanged();
                return this;
            }



            public Builder clearSumAcceleration() {

                sumAcceleration_ = 0D;
                onChanged();
                return this;
            }

            private double realSpeed_;



            public double getRealSpeed() {
                return realSpeed_;
            }



            public Builder setRealSpeed(double value) {

                realSpeed_ = value;
                onChanged();
                return this;
            }



            public Builder clearRealSpeed() {

                realSpeed_ = 0D;
                onChanged();
                return this;
            }

            private long direction1_;



            public long getDirection1() {
                return direction1_;
            }



            public Builder setDirection1(long value) {

                direction1_ = value;
                onChanged();
                return this;
            }



            public Builder clearDirection1() {

                direction1_ = 0L;
                onChanged();
                return this;
            }

            private Object postDate_ = "";



            public String getPostDate() {
                Object ref = postDate_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    postDate_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }



            public com.google.protobuf.ByteString
            getPostDateBytes() {
                Object ref = postDate_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    postDate_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }



            public Builder setPostDate(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                postDate_ = value;
                onChanged();
                return this;
            }



            public Builder clearPostDate() {

                postDate_ = getDefaultInstance().getPostDate();
                onChanged();
                return this;
            }



            public Builder setPostDateBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                postDate_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:protocol.OdpTripTrackerInfoDto)
        }

        // @@protoc_insertion_point(class_scope:protocol.OdpTripTrackerInfoDto)
        private static final com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto();
        }

        public static com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<OdpTripTrackerInfoDto>
                PARSER = new com.google.protobuf.AbstractParser<OdpTripTrackerInfoDto>() {
            public OdpTripTrackerInfoDto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new OdpTripTrackerInfoDto(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<OdpTripTrackerInfoDto> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<OdpTripTrackerInfoDto> getParserForType() {
            return PARSER;
        }

        public com.taraan.dum.dto.protobuf.TripTrackerInfoProtocol.OdpTripTrackerInfoDto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protocol_TripTrackerInfoDtos_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protocol_TripTrackerInfoDtos_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protocol_OdpTripTrackerInfoDto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protocol_OdpTripTrackerInfoDto_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\026TripTrackerProto.proto\022\010protocol\"S\n\023Tr" +
                        "ipTrackerInfoDtos\022<\n\023odpTripTrackerInfos" +
                        "\030\004 \003(\0132\037.protocol.OdpTripTrackerInfoDto\"" +
                        "\320\001\n\025OdpTripTrackerInfoDto\022\r\n\005order\030\001 \001(\003" +
                        "\022\020\n\010deviceId\030\002 \001(\t\022\021\n\tlongitude\030\003 \001(\001\022\020\n" +
                        "\010latitude\030\004 \001(\001\022\t\n\001x\030\005 \001(\001\022\t\n\001y\030\006 \001(\001\022\t\n" +
                        "\001z\030\007 \001(\001\022\027\n\017sumAcceleration\030\010 \001(\001\022\021\n\trea" +
                        "lSpeed\030\t \001(\001\022\022\n\ndirection1\030\n \001(\003\022\020\n\010post" +
                        "Date\030\013 \001(\tB5\n\032com.taraan.dum.dto.protobuf" +
                        "B\027TripTrackerInfoProtocolb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_protocol_TripTrackerInfoDtos_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_protocol_TripTrackerInfoDtos_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protocol_TripTrackerInfoDtos_descriptor,
                new String[]{"OdpTripTrackerInfos",});
        internal_static_protocol_OdpTripTrackerInfoDto_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_protocol_OdpTripTrackerInfoDto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protocol_OdpTripTrackerInfoDto_descriptor,
                new String[]{"Order", "DeviceId", "Longitude", "Latitude", "X", "Y", "Z", "SumAcceleration", "RealSpeed", "Direction1", "PostDate",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
